project_id: "261564"
api_token_env: BLOOM_CROWDIN_TOKEN
base_path: "./"
preserve_hierarchy: true
files: [
        {
            "source": "/en/messages.json",
            "translation": "/bloom-player/%two_letters_code%/messages.json",
            "dest": "bloom-player/%original_file_name%",
            "skip_untranslated_strings": true,
            # we decided not to do this because we lost approvals when manually relocating files
            # "export_only_approved": true,
        },
    ]
